services:
  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - "8883:8883"
    volumes:
      - ./mosquitto/mosquitto.prod.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/passwd:/etc/mosquitto/passwd
      - ./mosquitto/acl:/etc/mosquitto/acl:ro
      - ./mosquitto/certs:/mosquitto/certs:ro
      - mosquitto_data:/mosquitto/data
  
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: unless-stopped
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - mosquitto
      - influxdb

  influxdb:
    image: influxdb:2.7
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:8086:8086"
    volumes:
      - ./.volumes/influxdb/:/var/lib/influxdb2
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mosquitto_data: