services:
  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - "8883:8883"
    volumes:
      - ./mosquitto/mosquitto.prod.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/passwd:/etc/mosquitto/passwd
      - ./mosquitto/acl:/etc/mosquitto/acl:ro
      - ./mosquitto/certs:/mosquitto/certs:ro
      - mosquitto_data:/mosquitto/data

volumes:
  mosquitto_data: