# ===========================================
# Mosquitto Configuration
# Secure MQTT with TLS and authentication
# ===========================================

# ----- Secure TLS listener -----
listener 8883
protocol mqtt

# ----- TLS/SSL (Let's Encrypt) -----
tls_version tlsv1.2

cafile /path/to/file.pem
certfile /path/to/file.pem
keyfile /path/to/file.pem

# ----- Authentication -----
# Disable anonymous access
allow_anonymous false
password_file /path/to/password/file

# ----- Access Control List -----
acl_file /path/to/acl/file

# ----- Persistence -----
persistence true
persistence_location /path/to/data/location

# ----- Maximum number of client connections -----
# Set low number since only a few clients expected
max_connections 10

# ----- Logging -----
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information

# Log failed authentication attempts
log_type subscribe
log_type unsubscribe